version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - app-network
    ports:
      - "4200:4200"  # Angular
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - app-network
    ports:
      - "3000:3000"  # API Server
    volumes:
      - .:/app
      - /app/node_modules
      - ./server-data:/app/server-data
    environment:
      - NODE_ENV=development
    command: npm run startServer 