# Базовый образ
FROM node:20.12-bookworm-slim

# Установка рабочей директории
WORKDIR /app

# Копирование package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование исходного кода
COPY . .

# Открываем порт для разработки
EXPOSE 4200
EXPOSE 3000

# Команда для запуска в режиме разработки
CMD ["npm", "run", "start:dev"] 